channel1:
  auto_water: false
  dry_point: 27.0
  enabled: true
  pump_speed: 0.5
  pump_time: 0.5
  warn_level: 0.2
  water_level: 0.15
  watering_delay: 60
  wet_point: 0.7
channel2:
  auto_water: false
  dry_point: 27.0
  enabled: true
  pump_speed: 0.5
  pump_time: 0.5
  warn_level: 0.5
  water_level: 0.4
  watering_delay: 60
  wet_point: 0.7
channel3:
  auto_water: false
  dry_point: 27.0
  enabled: true
  pump_speed: 0.5
  pump_time: 0.5
  warn_level: 0.4
  water_level: 0.3
  watering_delay: 60
  wet_point: 0.7
general:
  alarm_enable: true
  alarm_interval: 2
  light_level_low: 4.0
  black_screen_when_light_low: false
